jointStates:
 topicName: '/ursa_joint_states'
 jointNames: [
   'ursa_shoulder_pan_joint',
   'ursa_shoulder_lift_joint',
   'ursa_elbow_joint',
   'ursa_wrist_1_joint',
   'ursa_wrist_2_joint',
   'ursa_wrist_3_joint',
 ]



